// js/modules/slidebuilder.js
(function(){
  'use strict';
  const MODE='slidebuilder';
  const ICON='./assets/icons/icon-slidebuilder.png';
  const ICON_ACTIVE='./assets/icons/icon-slidebuilder-selected.png';
  const TEMPLATE_PATH='./assets/ppt/slidebuilder/template-slide-grafico.pptx';
  const COLORS={red:'C4162B',burgundy:'4C1428',rose:'E9A0A7',tortora:'EAE3DA',black:'1A171B',grayDark:'787878',grayLight:'E8E8E8',bg:'F3F1EF'};
  const PALETTE=[COLORS.red,COLORS.burgundy,COLORS.rose,COLORS.tortora,COLORS.black,COLORS.grayDark];
  const DEFAULTS={
    graph:'Categoria,Valore
Milano,35
Roma,22
Torino,18
Bologna,12',
    timeline:'Data,Titolo,Dettaglio
Gen 2026,Acquisizione,Avvio progetto
Feb 2026,Strategia,Definizione concept
Mar 2026,Campagna,Attivazione canali
Apr 2026,Lancio,Go-live',
    table:'Indicatore,Q1,Q2,Q3,Q4
Lead,120,145,162,188
Appuntamenti,34,38,41,47
Vendite,5,7,8,10'
  };
  let state={type:'graph',chartType:'bar',title:'Inserire qui il titolo',description:'Inserire piccola descrizione',source:'inserire qui fonte.',dataText:DEFAULTS.graph,parsed:null};
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  function currentUser(){try{return window.Auth&&typeof window.Auth.current==='function'?window.Auth.current():null;}catch{return null;}}
  function isAdmin(){return (currentUser()?.role||'')==='admin';}
  function notify(msg,isError){try{if(typeof window.showToast==='function') return window.showToast(msg,isError?'error':'ok');}catch{}; isError?console.error(msg):console.log(msg);}
  function detectDelimiter(text){const first=String(text||'').split(/?
/).find(Boolean)||''; if(first.includes('	')) return '	'; return ((first.match(/;/g)||[]).length > (first.match(/,/g)||[]).length) ? ';' : ',';}
  function parseRows(text){const raw=String(text||'').trim(); if(!raw) return []; const d=detectDelimiter(raw); return raw.split(/?
/).map(l=>l.trim()).filter(Boolean).map(line=>line.split(d).map(c=>c.trim()));}
  function isNumberish(value){const cleaned=String(value||'').replace(/\./g,'').replace(',','.').replace(/%/g,'').trim(); return cleaned!=='' && !Number.isNaN(Number(cleaned));}
  function toNumber(value){const cleaned=String(value||'').replace(/\./g,'').replace(',','.').replace(/%/g,'').trim(); const n=Number(cleaned); return Number.isFinite(n)?n:0;}
  function parseGraph(text){const rows=parseRows(text); if(!rows.length) return {labels:[],values:[]}; let body=rows; if(rows.length>1){const second=rows[0][1]||''; const first=String(rows[0][0]||'').toLowerCase(); if(!isNumberish(second)||['categoria','label','nome','mese','tipo'].includes(first)) body=rows.slice(1);} const labels=[],values=[]; body.forEach(r=>{const label=r[0]||''; const value=r[1]; if(!label||!isNumberish(value)) return; labels.push(label); values.push(toNumber(value));}); return {labels,values};}
  function parseTimeline(text){const rows=parseRows(text); if(!rows.length) return {items:[]}; let body=rows; if(rows.length>1){const c0=String(rows[0][0]||'').toLowerCase(); const c1=String(rows[0][1]||'').toLowerCase(); if(['data','date','periodo'].includes(c0)||['titolo','title','fase'].includes(c1)) body=rows.slice(1);} return {items: body.map(r=>({date:r[0]||'',title:r[1]||'',detail:r[2]||''})).filter(x=>x.date||x.title||x.detail)};}
  function parseTable(text){const rows=parseRows(text); if(!rows.length) return {headers:[],rows:[]}; return {headers:rows[0]||[], rows:rows.slice(1).filter(r=>r.some(Boolean))};}
  function parseCurrent(){try{return state.type==='graph'?parseGraph(state.dataText):state.type==='timeline'?parseTimeline(state.dataText):parseTable(state.dataText);}catch{return null;}}
  function esc(text){return String(text||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function svgDataUri(svg){return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);}
  function barSvg(data){const labels=data.labels||[], values=data.values||[]; const W=1100,H=620,left=76,right=24,top=32,bottom=92,plotW=W-left-right,plotH=H-top-bottom,max=Math.max(...values,1),barW=labels.length?Math.min(88,plotW/labels.length*.58):40,gap=labels.length?plotW/labels.length:60; let out=''; [0.25,0.5,0.75,1].forEach(step=>{const y=top+plotH-(plotH*step); out+=`<line x1="${left}" y1="${y.toFixed(1)}" x2="${W-right}" y2="${y.toFixed(1)}" stroke="#BEBAB5" stroke-opacity="0.45" stroke-width="1" />`; out+=`<text x="${left-10}" y="${y+4}" text-anchor="end" font-family="Manrope, Arial" font-size="15" fill="#787878">${Math.round(max*step)}</text>`;}); labels.forEach((label,i)=>{const val=values[i]||0,h=(val/max)*plotH,x=left+i*gap+(gap-barW)/2,y=top+plotH-h,color='#'+PALETTE[i%PALETTE.length]; out+=`<rect x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${barW.toFixed(1)}" height="${h.toFixed(1)}" rx="12" fill="${color}" />`; out+=`<text x="${(x+barW/2).toFixed(1)}" y="${(y-10).toFixed(1)}" text-anchor="middle" font-family="Manrope, Arial" font-size="16" font-weight="700" fill="#1A171B">${val}</text>`; out+=`<text x="${(x+barW/2).toFixed(1)}" y="${H-36}" text-anchor="middle" font-family="Manrope, Arial" font-size="15" fill="#1A171B">${esc(label)}</text>`;}); return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="transparent"/>${out}<line x1="${left}" y1="${top+plotH}" x2="${W-right}" y2="${top+plotH}" stroke="#9F9A95" stroke-width="1.4"/></svg>`;}
  function polarToCartesian(cx,cy,r,angle){const rad=(angle-90)*Math.PI/180; return {x:cx+r*Math.cos(rad),y:cy+r*Math.sin(rad)};}
  function makeArcPath(cx,cy,rOuter,rInner,startAngle,endAngle){const outerStart=polarToCartesian(cx,cy,rOuter,endAngle), outerEnd=polarToCartesian(cx,cy,rOuter,startAngle), innerStart=polarToCartesian(cx,cy,rInner,startAngle), innerEnd=polarToCartesian(cx,cy,rInner,endAngle), largeArc=endAngle-startAngle<=180?'0':'1'; if(rInner<=0){return `M ${cx} ${cy} L ${outerStart.x} ${outerStart.y} A ${rOuter} ${rOuter} 0 ${largeArc} 0 ${outerEnd.x} ${outerEnd.y} Z`; } return [`M ${outerStart.x} ${outerStart.y}`,`A ${rOuter} ${rOuter} 0 ${largeArc} 0 ${outerEnd.x} ${outerEnd.y}`,`L ${innerStart.x} ${innerStart.y}`,`A ${rInner} ${rInner} 0 ${largeArc} 1 ${innerEnd.x} ${innerEnd.y}`,'Z'].join(' ');}
  function pieSvg(data,doughnut){const labels=data.labels||[],values=data.values||[],total=values.reduce((a,b)=>a+b,0)||1,W=1100,H=620,cx=325,cy=310,rOuter=182,rInner=doughnut?100:0; let angle=0,slices='',legend=''; labels.forEach((label,i)=>{const value=values[i]||0,pct=(value/total)*100,next=angle+(value/total)*360,color='#'+PALETTE[i%PALETTE.length]; slices+=`<path d="${makeArcPath(cx,cy,rOuter,rInner,angle,next)}" fill="${color}" />`; const mid=angle+(next-angle)/2,p=polarToCartesian(cx,cy,doughnut?145:120,mid); slices+=`<text x="${p.x.toFixed(1)}" y="${p.y.toFixed(1)}" text-anchor="middle" font-family="Manrope, Arial" font-size="14" font-weight="700" fill="#1A171B">${pct.toFixed(0)}%</text>`; const ly=150+i*62; legend+=`<rect x="640" y="${ly-14}" width="22" height="22" rx="6" fill="${color}" /><text x="675" y="${ly}" font-family="Manrope, Arial" font-size="18" fill="#1A171B">${esc(label)}</text><text x="980" y="${ly}" text-anchor="end" font-family="Manrope, Arial" font-size="18" font-weight="700" fill="#4C1428">${value}</text>`; angle=next;}); return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="transparent"/>${slices}${legend}</svg>`;}
  function lineSvg(data){const labels=data.labels||[], values=data.values||[], W=1100,H=620,left=76,right=24,top=42,bottom=92,plotW=W-left-right,plotH=H-top-bottom,max=Math.max(...values,1),min=Math.min(...values,0),span=Math.max(max-min,1), xs=labels.map((_,i)=>left+(plotW*i)/Math.max(labels.length-1,1)), ys=values.map(v=>top+plotH-((v-min)/span)*plotH); const points=xs.map((x,i)=>`${x.toFixed(1)},${ys[i].toFixed(1)}`).join(' '); let guides='', labelsSvg='', pts=''; [0,0.25,0.5,0.75,1].forEach(step=>{const y=top+plotH-plotH*step,label=Math.round(min+step*span); guides+=`<line x1="${left}" y1="${y.toFixed(1)}" x2="${W-right}" y2="${y.toFixed(1)}" stroke="#CFCAC5" stroke-opacity="0.5" stroke-width="1" /><text x="${left-10}" y="${y+4}" text-anchor="end" font-family="Manrope, Arial" font-size="15" fill="#787878">${label}</text>`;}); labels.forEach((label,i)=>{labelsSvg+=`<text x="${xs[i].toFixed(1)}" y="${H-34}" text-anchor="middle" font-family="Manrope, Arial" font-size="15" fill="#1A171B">${esc(label)}</text>`; pts+=`<circle cx="${xs[i].toFixed(1)}" cy="${ys[i].toFixed(1)}" r="6" fill="#C4162B" stroke="#fff" stroke-width="3" /><text x="${xs[i].toFixed(1)}" y="${(ys[i]-14).toFixed(1)}" text-anchor="middle" font-family="Manrope, Arial" font-size="14" font-weight="700" fill="#1A171B">${values[i]}</text>`;}); return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="transparent"/>${guides}<polyline fill="none" stroke="#4C1428" stroke-width="4" points="${points}" stroke-linecap="round" stroke-linejoin="round" />${pts}${labelsSvg}</svg>`;}
  function timelineSvg(data){const items=data.items||[],W=1100,H=620,startX=110,endX=1000,centerY=320,gap=items.length>1?(endX-startX)/(items.length-1):0; let body=`<line x1="${startX}" y1="${centerY}" x2="${endX}" y2="${centerY}" stroke="#D5CEC7" stroke-width="8" stroke-linecap="round" />`; items.forEach((item,i)=>{const x=startX+gap*i,isTop=i%2===0,boxY=isTop?112:382,anchorY=isTop?boxY+88:boxY-18,color=i%3===0?'#'+COLORS.red:(i%3===1?'#'+COLORS.burgundy:'#'+COLORS.rose); body+=`<line x1="${x}" y1="${centerY}" x2="${x}" y2="${anchorY}" stroke="#B29A9F" stroke-width="2" /><circle cx="${x}" cy="${centerY}" r="14" fill="${color}" stroke="#fff" stroke-width="5" /><rect x="${x-128}" y="${boxY}" rx="16" width="256" height="106" fill="#ffffff" stroke="#E3DDD6" /><text x="${x-108}" y="${boxY+26}" font-family="Manrope, Arial" font-size="16" font-weight="700" fill="#C4162B">${esc(item.date)}</text><text x="${x-108}" y="${boxY+52}" font-family="PP Pangaia, Georgia, serif" font-size="22" font-weight="600" fill="#4C1428">${esc(item.title)}</text><text x="${x-108}" y="${boxY+78}" font-family="Manrope, Arial" font-size="14" fill="#1A171B">${esc(item.detail)}</text>`;}); return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="transparent"/>${body}</svg>`;}
  function renderTableHtml(data){const headers=data.headers||[],rows=data.rows||[]; if(!headers.length) return '<div class="sb-empty">Inserisci almeno una riga di intestazione e una riga dati.</div>'; const head='<tr>'+headers.map(h=>`<th>${esc(h)}</th>`).join('')+'</tr>'; const body=rows.map(r=>'<tr>'+headers.map((_,i)=>`<td>${esc(r[i]||'')}</td>`).join('')+'</tr>').join(''); return `<table><thead>${head}</thead><tbody>${body}</tbody></table>`;}
  function currentSvg(){const p=state.parsed; if(!p) return ''; if(state.type==='graph'){ if(!p.labels?.length) return ''; if(state.chartType==='pie') return pieSvg(p,false); if(state.chartType==='doughnut') return pieSvg(p,true); if(state.chartType==='line') return lineSvg(p); return barSvg(p);} if(state.type==='timeline'){ if(!p.items?.length) return ''; return timelineSvg(p);} return '';}
  function metrics(parsed){const mount=$('#SbKpis'); if(!mount) return; if(!parsed){mount.innerHTML='';return;} if(state.type==='graph'){const total=(parsed.values||[]).reduce((a,b)=>a+b,0); const topIdx=(parsed.values||[]).reduce((best,v,i,arr)=>v>(arr[best]||-Infinity)?i:best,0); mount.innerHTML=`<div class="sb-kpi"><strong>${parsed.labels.length}</strong><span>Categorie</span></div><div class="sb-kpi"><strong>${total}</strong><span>Valore totale</span></div><div class="sb-kpi"><strong>${esc(parsed.labels[topIdx]||'—')}</strong><span>Categoria top</span></div>`; return;} if(state.type==='timeline'){mount.innerHTML=`<div class="sb-kpi"><strong>${parsed.items.length}</strong><span>Milestone</span></div><div class="sb-kpi"><strong>${esc(parsed.items[0]?.date||'—')}</strong><span>Inizio</span></div><div class="sb-kpi"><strong>${esc(parsed.items[parsed.items.length-1]?.date||'—')}</strong><span>Fine</span></div>`; return;} mount.innerHTML=`<div class="sb-kpi"><strong>${parsed.headers.length}</strong><span>Colonne</span></div><div class="sb-kpi"><strong>${parsed.rows.length}</strong><span>Righe dati</span></div><div class="sb-kpi"><strong>${esc(parsed.headers[0]||'—')}</strong><span>Prima intestazione</span></div>`;}
  function syncStateFromUi(){state.title=($('#SbTitle')?.value||'').trim()||'Inserire qui il titolo'; state.description=($('#SbDescription')?.value||'').trim()||'Inserire piccola descrizione'; state.source=($('#SbSource')?.value||'').trim()||'inserire qui fonte.'; state.chartType=$('.sb-chart-switch .sb-switch-btn.active')?.dataset.chart||'bar'; state.dataText=$('#SbData')?.value||''; state.parsed=parseCurrent();}
  function refreshPreview(){syncStateFromUi(); $('#SbPreviewTitle').textContent=state.title; $('#SbPreviewDescription').textContent=state.description; $('#SbPreviewFootnote').textContent=`© 2026 Abitare Co. | All rights reserved.  Fonte: ${state.source}`; const svgWrap=$('#SbPreviewSvg'), tableWrap=$('#SbPreviewTable'); if(state.type==='table'){svgWrap.innerHTML=''; tableWrap.innerHTML=renderTableHtml(state.parsed||{headers:[],rows:[]}); tableWrap.classList.remove('hidden'); svgWrap.classList.add('hidden');} else {const svg=currentSvg(); svgWrap.innerHTML=svg||'<div class="sb-empty">Inserisci dati validi per vedere la preview.</div>'; tableWrap.classList.add('hidden'); svgWrap.classList.remove('hidden');} metrics(state.parsed);}
  function inputHint(){if(state.type==='graph') return 'Puoi incollare due colonne da Excel. Formato veloce: <code>Categoria,Valore</code>. Supporta anche tab o ;'; if(state.type==='timeline') return 'Formato consigliato: <code>Data,Titolo,Dettaglio</code>. Una riga = una milestone.'; return 'Formato tabellare: prima riga = intestazioni, righe successive = dati.';}
  function setType(type){state.type=type; $('#SbData').value=DEFAULTS[type]||''; $('#SbDataHelp').innerHTML=inputHint(); $('#SbChartPanel').classList.toggle('hidden',type!=='graph'); $$('.sb-type-switch .sb-switch-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.type===type)); refreshPreview();}
  async function exportPpt(){syncStateFromUi(); if(!window.PptxGenJS){notify('Libreria PPT non disponibile. Ricarica la pagina.',true); return;} if(!state.parsed){notify('Inserisci dati validi prima di esportare.',true); return;} const pptx=new window.PptxGenJS(); pptx.layout='LAYOUT_WIDE'; pptx.author='Abitare Co.'; pptx.company='Abitare Co.'; pptx.subject='Slide Builder'; pptx.title=state.title; pptx.lang='it-IT'; pptx.theme={headFontFace:'PP Pangaia',bodyFontFace:'Manrope',lang:'it-IT'}; const slide=pptx.addSlide(); slide.background={color:COLORS.bg}; slide.addText(state.title,{x:1.35,y:.28,w:10.65,h:.65,align:'center',valign:'mid',fontFace:'PP Pangaia',fontSize:29,bold:true,color:COLORS.burgundy,margin:0}); slide.addText(state.description,{x:2.0,y:1.16,w:9.3,h:.28,align:'center',valign:'mid',fontFace:'Manrope',fontSize:11,color:COLORS.burgundy,margin:0}); const area={x:.88,y:1.82,w:11.57,h:4.72}; if(state.type==='table'){const rows=[state.parsed.headers,...state.parsed.rows]; slide.addTable(rows,{x:area.x,y:area.y,w:area.w,h:area.h,border:{type:'solid',color:'D8D1CA',pt:.75},fontFace:'Manrope',fontSize:11,color:COLORS.black,fill:COLORS.tortora,margin:.08,rowH:.37,autoFit:true,fillHeader:COLORS.burgundy,colorHeader:'FFFFFF',boldHeader:true,valign:'mid'});} else {const svg=currentSvg(); if(!svg){notify('Inserisci dati validi prima di esportare.',true); return;} slide.addImage({data:svgDataUri(svg),x:area.x,y:area.y,w:area.w,h:area.h});}
    slide.addText(`© 2026 Abitare Co. | All rights reserved.  Fonte: ${state.source}`,{x:.08,y:7.02,w:7.2,h:.18,fontFace:'Manrope',fontSize:7.4,color:'6E6A67',margin:0});
    try{ slide.addImage({path:'./assets/logo.png',x:11.86,y:6.78,w:1.22,h:.32}); } catch(err){ slide.addText('Abitare co.',{x:11.65,y:6.76,w:1.45,h:.28,fontFace:'Times New Roman',fontSize:18,color:COLORS.black,margin:0,align:'right'}); }
    const safeName=String(state.title||'slide-builder').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,42)||'slide-builder';
    await pptx.writeFile({fileName:`${safeName}.pptx`});
    notify('PPT esportato con successo.');
  }
  function injectMenuItem(){const menu=document.getElementById('SideMenu'); if(!menu||menu.querySelector(`li[data-mode="${MODE}"]`)) return; const li=document.createElement('li'); li.dataset.mode=MODE; li.dataset.icon=ICON; li.dataset.iconActive=ICON_ACTIVE; li.innerHTML=`<span class="mi"><img alt="" src="${ICON}" /></span><span class="txt">Slide Builder</span>`; const pptLi=menu.querySelector('li[data-mode="ppt"]'); if(pptLi&&pptLi.parentNode) pptLi.parentNode.insertBefore(li,pptLi); else menu.appendChild(li);}
  function cardMarkup(){return `<section id="SlideBuilderCard" class="card hidden slidebuilder-card"><div class="sb-head"><div class="sb-title-wrap"><h3>Slide Builder</h3><p>Crea una slide PPT già brandizzata Abitare Co. con grafici, timeline o tabelle pronte per la presentazione.</p></div><div class="sb-badge">Admin only · v1 launch</div></div><div class="sb-grid"><div><div class="sb-panel"><h4>1. Tipo contenuto</h4><div class="sb-type-switch"><button type="button" class="sb-switch-btn active" data-type="graph">Grafico</button><button type="button" class="sb-switch-btn" data-type="timeline">Timeline</button><button type="button" class="sb-switch-btn" data-type="table">Tabella</button></div></div><div class="sb-panel" id="SbChartPanel"><h4>2. Tipo grafico</h4><div class="sb-chart-switch"><button type="button" class="sb-switch-btn active" data-chart="bar">Barre</button><button type="button" class="sb-switch-btn" data-chart="line">Linea</button><button type="button" class="sb-switch-btn" data-chart="pie">Torta</button><button type="button" class="sb-switch-btn" data-chart="doughnut">Doughnut</button></div></div><div class="sb-panel"><h4>3. Testi slide</h4><div class="sb-row"><div><label for="SbTitle">Titolo</label><input id="SbTitle" class="input" type="text" value="Inserire qui il titolo" /></div><div><label for="SbSource">Fonte</label><input id="SbSource" class="input" type="text" value="inserire qui fonte." /></div></div><div><label for="SbDescription">Descrizione breve</label><input id="SbDescription" class="input" type="text" value="Inserire piccola descrizione" /></div></div><div class="sb-panel"><div class="sb-meta"><h4>4. Dati</h4><div class="sb-badge">Palette Abitare Co. default</div></div><textarea id="SbData" class="sb-textarea"></textarea><div id="SbDataHelp" class="sb-help"></div></div></div><div class="sb-preview-wrap"><div class="sb-panel"><div class="sb-meta"><h4>Preview slide</h4><div class="sb-badge">Layout grafico v1</div></div><div class="sb-preview-stage"><div class="sb-preview-slide"><div id="SbPreviewTitle" class="sb-preview-title"></div><div id="SbPreviewDescription" class="sb-preview-desc"></div><div class="sb-preview-content"><div id="SbPreviewSvg" class="sb-preview-svg"></div><div id="SbPreviewTable" class="sb-preview-table hidden"></div></div><div class="sb-preview-footer"><div id="SbPreviewFootnote" class="sb-preview-footnote"></div><div class="sb-preview-logo">Abitare <b>co.</b></div></div></div></div></div><div class="sb-panel"><h4>Indicatori rapidi</h4><div id="SbKpis" class="sb-kpis"></div></div><div class="sb-panel"><h4>Template di riferimento</h4><p class="sb-empty">Il file <code>${TEMPLATE_PATH}</code> è incluso nel pacchetto GitHub come riferimento ufficiale del layout slide. La v1 genera però la slide direttamente via codice, così l'export resta stabile e non tocca le altre funzioni.</p></div></div></div></section>`;}
  function injectCard(){const mount=document.querySelector('.cards-scroll'); if(!mount||document.getElementById('SlideBuilderCard')) return; mount.insertAdjacentHTML('beforeend',cardMarkup());}
  function bindUi(){const card=document.getElementById('SlideBuilderCard'); if(!card||card.dataset.bound==='1') return; card.dataset.bound='1'; $('#SbData',card).value=DEFAULTS.graph; $('#SbDataHelp',card).innerHTML=inputHint(); card.addEventListener('click',e=>{const typeBtn=e.target.closest('.sb-type-switch .sb-switch-btn'); if(typeBtn){setType(typeBtn.dataset.type); return;} const chartBtn=e.target.closest('.sb-chart-switch .sb-switch-btn'); if(chartBtn){$$('.sb-chart-switch .sb-switch-btn',card).forEach(btn=>btn.classList.toggle('active',btn===chartBtn)); refreshPreview();}}); ['SbTitle','SbDescription','SbSource','SbData'].forEach(id=>{const el=document.getElementById(id); if(!el) return; el.addEventListener('input',refreshPreview); el.addEventListener('change',refreshPreview);}); const btn=document.getElementById('BtnProcedi'); if(btn&&!btn.dataset.slidebuilderCapture){btn.dataset.slidebuilderCapture='1'; btn.addEventListener('click',e=>{if((window.currentMode||'')!==MODE) return; e.preventDefault(); e.stopPropagation(); e.stopImmediatePropagation(); exportPpt();},true);} refreshPreview();}
  function showCard(){const card=document.getElementById('SlideBuilderCard'); const btn=document.getElementById('BtnProcedi'); if(card) card.classList.remove('hidden'); if(btn){btn.classList.remove('hidden'); btn.textContent='Esporta PPT';}}
  function patchSelectMode(){if(!window.selectMode||window.selectMode.__slidebuilder) return; const orig=window.selectMode; const wrapped=function(mode){const res=orig.apply(this,arguments); if(mode===MODE) showCard(); return res;}; wrapped.__slidebuilder=true; window.selectMode=wrapped;}
  function initWhenReady(){if(!isAdmin()) return; injectMenuItem(); injectCard(); bindUi(); patchSelectMode();}
  function bootstrap(){let tries=0; const t=setInterval(()=>{tries++; initWhenReady(); if(document.getElementById('SlideBuilderCard')&&window.selectMode) clearInterval(t); if(tries>120) clearInterval(t);},80);} 
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',bootstrap); else bootstrap();
})();
